### ISSUE TITLE
Width issues?

### ISSUE THREAD

**Issue by dartharaknus** [Michsky/looader#1]
Are you loading the scene completely? I am having some issues with camera. And also, the loading screen is not taking the full height of the screen. My resolution is 2560x1440.

**Comment by dartharaknus** [comment]
When I actually build it, the loader background takes up the whole screen. So, this issue is only when I am testing my game in the unity editor.

**Comment by Michsky** [comment]
Oh boy, I just realized there was an issue, sorry for a looong time, I didn't get a notification from github... Anyways, glad you solved your problem!
